# Generated by Django 2.1.3 on 2018-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.CharField(max_length=200, verbose_name='Data de criação'),
        ),
    ]
