# Generated by Django 2.1 on 2018-08-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20180830_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AlterModelOptions(
            name='questionario',
            options={'verbose_name': 'Questionário', 'verbose_name_plural': 'Questionários'},
        ),
    ]
