# Generated by Django 2.1 on 2018-08-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_auto_20180830_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='administracao.Escola'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas', to='administracao.Acao'),
        ),
    ]
