# Generated by Django 2.1 on 2018-08-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_auto_20180831_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='latitude',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=22, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='escola',
            name='longitude',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=22, verbose_name='Longitude'),
        ),
    ]
