# Generated by Django 2.1.1 on 2018-09-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_auto_20180831_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dente',
            name='carie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentes', to='administracao.Carie'),
        ),
        migrations.AlterField(
            model_name='gengiva',
            name='periodontal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gengivas', to='administracao.Periodontal'),
        ),
    ]
