# Generated by Django 2.1.3 on 2018-11-12 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0008_auto_20181111_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='questao_1',
            field=models.CharField(blank=True, choices=[('0', 'Ensino Fundamental'), ('1', 'Ensino Médio'), ('2', 'Ensino Médio Técnico'), ('3', 'Ensino Superior'), ('4', 'Pós-graduação'), ('5', 'Não sei')], max_length=2, null=True, verbose_name='01. Qual o grau de escolaridade mais elevado que você pretende concluir?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_10',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='10. Alguém que mora na sua casa tem carro?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_100',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maior parte do tempo'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='100. Nos últimos 30 dias, com que frequência seus pais ou responsáveis mexeram em suas coisas sem a sua concordância?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_101',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maior parte do tempo'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='101. Nos últimos 30 dias, com que frequência os colegas de sua escola trataram você bem e/ou foram prestativos com você?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_102',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maior parte do tempo'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='102. Nos últimos 30 dias, com que frequência algum dos seus colegas de escola lhe esculacharam, zoaram, mangaram, intimidaram ou caçoaram tanto que você ficou magoado, incomodado, aborrecido, ofendido ou humilhado?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_103',
            field=models.CharField(blank=True, choices=[('0', 'A minha cor ou raça'), ('1', 'A minha religião'), ('2', 'A aparência do meu rosto'), ('3', 'A aparência do meu corpo'), ('4', 'A minha orientação sexual'), ('5', 'A minha região de origem'), ('6', 'Outros motivos/causas')], max_length=2, null=True, verbose_name='103. Nos últimos 30 dias, qual o motivo ou causa de seus colegas terem lhe esculachado, zombado, zoado, caçoado, mangado, intimidado ou humilhado?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_104',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='104. Nos últimos 30 dias, você esculachou, zombou, mangou, intimidou ou caçoou algum de seus colegas da escola tanto que ele ficou magoado, aborrecido, ofendido ou humilhado?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_105',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não'), ('2', 'Não sei o que é bullying'), ('3', 'Sempre')], max_length=2, null=True, verbose_name='105. Você já sofreu bullying?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_106',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maioria das vezes'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='106. Nos ultimos 12 meses, com que frequência você não conseguiu dormir à noite porque algo o(a) preocupava muito?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_107',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum amigo (0)'), ('1', '1 amigo'), ('2', '2 amigos'), ('3', '3 ou mais amigos')], max_length=2, null=True, verbose_name='107. Quantos amigos(as) próximos você tem?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_108',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maioria das vezes'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='108. Nos últimos 30 dias, com que frequência você lavou as mãos antes de comer?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_109',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maioria das vezes'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='109. Nos últimos 30 dias, com que frequência você lavou as mãos após usar o banheiro ou o vaso sanitário?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_11',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='11. Alguém que mora na sua casa tem moto?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_110',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maioria das vezes'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='110. Nos últimos 30 dias, com que frequência você usou sabão ou sabonete quando lavou suas mãos?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_111',
            field=models.CharField(blank=True, choices=[('0', 'Não escovei meus dentes nos últimos 30 dias'), ('1', 'Não escovei meus dentes diariamente'), ('2', '1 vez por dia nos últimos 30 dias'), ('3', '2 vezes por dia nos últimos 30 dias'), ('4', '3 vezes por dia nos últimos 30 dias'), ('5', '4 ou mais vezes por dia nos últimos 30 dias')], max_length=2, null=True, verbose_name='111. Nos últimos 30 dias, quantas vezes por dia você usualmente escovou os dentes?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_112',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não'), ('2', 'Não sei / não me lembro')], max_length=2, null=True, verbose_name='112. Nos últimos 06 meses, você teve dor de dente? (Não vale aquela dor de dente causada por uso de aparelho para correção dos dentes, isto é, aparelhos ortodônticos).)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_113',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez nos últimos 12 meses (0 vez)'), ('1', '1 vez nos últimos 12 meses'), ('2', '2 vezes nos últimos 12 meses'), ('3', '3 ou mais vezes nos últimos 12 meses')], max_length=2, null=True, verbose_name='113. Nos últimos 12 meses, quantas vezes você foi ao dentista?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_114',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 dia nos últimos 30 dias'), ('2', '2 dias nos últimos 30 dias'), ('3', '3 dias nos últimos 30 dias'), ('4', '4 dias nos últimos 30 dias'), ('5', '5 dias ou mais nos últimos 30 dias')], max_length=2, null=True, verbose_name='114. Nos últimos 30 dias, em quantos dias você deixou de ir à escola porque não se sentia seguro no caminho de casa para a escola ou da escola para casa?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_115',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 dia nos últimos 30 dias'), ('2', '2 dias nos últimos 30 dias'), ('3', '3 dias nos últimos 30 dias'), ('4', '4 dias nos últimos 30 dias'), ('5', '5 dias ou mais nos últimos 30 dias')], max_length=2, null=True, verbose_name='115. Nos últimos 30 dias, em quantos dias você não foi à escola porque não se sentia seguro na escola?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_116',
            field=models.CharField(blank=True, choices=[('0', 'Não andei nesse tipo de veículo no banco da frente nos últimos 30 dias'), ('1', 'Nunca uso cinto de segurança'), ('2', 'Raramente'), ('3', 'Às vezes'), ('4', 'Na maior parte do tempo'), ('5', 'Sempre')], max_length=2, null=True, verbose_name='116. Nos últimos 30 dias, com que frequência você usou cinto de segurança enquanto andava como passageiro(a) no banco da frente de carro/automóvel, van ou táxi?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_117',
            field=models.CharField(blank=True, choices=[('0', 'Não andei de motocicleta nos últimos 30 dias.'), ('1', 'Nunca uso capacete'), ('2', 'Raramente'), ('3', 'Às vezes'), ('4', 'Na maior parte do tempo'), ('5', 'Sempre')], max_length=2, null=True, verbose_name='117. Nos últimos 30 dias, com que frequência você usou capacete ao andar de motocicleta?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_118',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez nos últimos 30 dias (0 vez)'), ('1', '1 vez nos últimos 30 dias'), ('2', '2 ou 3 vezes nos últimos 30 dias'), ('3', '4 ou 5 vezes nos últimos 30 dias'), ('4', '6 ou mais vezes nos últimos 30 dias')], max_length=2, null=True, verbose_name='118. Nos últimos 30 dias, quantas vezes você dirigiu um veículo motorizado de transporte? (carro, motocicleta, voadeira, barco, etc.)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_119',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez nos últimos 30 dias (0 vez)'), ('1', '1 vez nos últimos 30 dias'), ('2', '2 ou 3 vezes nos últimos 30 dias'), ('3', '4 ou 5 vezes nos últimos 30 dias'), ('4', '6 ou mais vezes nos últimos 30 dias')], max_length=2, null=True, verbose_name='119. Nos últimos 30 dias, quantas vezes você andou em carro ou outro veículo motorizado dirigido por alguém que tinha consumido alguma bebida alcoólica?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_12',
            field=models.CharField(blank=True, choices=[('0', 'Não tem banheiro com chuveiro dentro da minha casa'), ('1', '1 banheiro'), ('2', '2 banheiros'), ('3', '3 banheiros'), ('4', '4 banheiros ou mais')], max_length=2, null=True, verbose_name='12. Quantos banheiros com chuveiro têm dentro da sua casa?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_120',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez nos últimos 30 dias (0 vez)'), ('1', '1 vez nos últimos 30 dias'), ('2', '2 ou 3 vezes nos últimos 30 dias'), ('3', '4 ou 5 vezes nos últimos 30 dias'), ('4', '6 ou 7 vezes nos últimos 30 dias'), ('5', '8 ou 9 vezes nos últimos 30 dias'), ('6', '10 ou 11 vezes nos últimos 30 dias'), ('7', '12 vezes ou mais nos últimos 30 dias')], max_length=2, null=True, verbose_name='120. Nos últimos 30 dias, quantas vezes você foi agredido(a) fisicamente por um adulto da sua família?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_121',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='121. Nos últimos 30 dias, você esteve envolvido(a) em alguma briga em que alguma pessoa usou arma de fogo, como revólver ou espingarda?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_122',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='122. Nos últimos 30 dias, você esteve envolvido(a) em alguma briga em que alguma pessoa usou alguma outra arma como faca, canivete, peixeira, pedra, pedaço de pau ou garrafa?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_123',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez nos últimos 12 meses (0 vez)'), ('1', '1 vez nos últimos 12 meses'), ('2', '2 a 3 vezes nos últimos 12 meses'), ('3', '4 a 5 vezes nos últimos 12 meses'), ('4', '6 a 7 vezes nos últimos 12 meses'), ('5', '8 a 9 vezes nos últimos 12 meses'), ('6', '10 a 11 vezes nos últimos 12 meses'), ('7', '12 ou mais vezes nos últimos 12 meses')], max_length=2, null=True, verbose_name='123. Nos últimos 12 meses, quantas vezes você foi agredido(a) fisicamente?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_124',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez nos últimos 12 meses (0 vez)'), ('1', '1 vez nos últimos 12 meses'), ('2', '2 a 3 vezes nos últimos 12 meses'), ('3', '4 a 5 vezes nos últimos 12 meses'), ('4', '6 a 7 vezes nos últimos 12 meses'), ('5', '8 a 9 vezes nos últimos 12 meses'), ('6', '10 a 11 vezes nos últimos 12 meses'), ('7', '12 ou mais vezes nos últimos 12 meses')], max_length=2, null=True, verbose_name='124. Nos últimos 12 meses, quantas vezes você se envolveu em briga (uma luta física)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_125',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez nos últimos 12 meses (0 vez)'), ('1', '1 vez nos últimos 12 meses'), ('2', '2 a 3 vezes nos últimos 12 meses'), ('3', '4 a 5 vezes nos últimos 12 meses'), ('4', '6 a 7 vezes nos últimos 12 meses'), ('5', '8 a 9 vezes nos últimos 12 meses'), ('6', '10 a 11 vezes nos últimos 12 meses'), ('7', '12 ou mais vezes nos últimos 12 meses')], max_length=2, null=True, verbose_name='125. Nos últimos 12 meses, quantas vezes você foi seriamente ferido(a) em uma briga?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_126',
            field=models.CharField(blank=True, choices=[('0', 'Não tive ferimento/lesão séria nos últimos 12 meses'), ('1', 'Tive um osso quebrado ou junta deslocada'), ('2', 'Tive um corte ou perfuração'), ('3', 'Tive um traumatismo ou outra lesão na cabeça ou pescoço e desmaiei ou não consegui respirar'), ('4', 'Tive um ferimento à bala (arma de fogo)'), ('5', 'Tive uma queimadura grave'), ('6', 'Fui envenenado(a) ou tive overdose (consumi drogas em excesso)'), ('7', 'Tive outra lesão ou machucado')], max_length=2, null=True, verbose_name='126. Nos últimos 12 meses, qual foi o ferimento ou a lesão mais séria que aconteceu com você?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_127',
            field=models.CharField(blank=True, choices=[('0', 'Foi um acidente ou atropelamento causado por veículo motorizado'), ('1', 'Foi algo que caiu sobre mim ou me atingiu'), ('2', 'Foi um ataque que sofri ou briga com alguém (com ou sem uso de arma)'), ('3', 'Foi um incêndio ou a proximidade com algo quente'), ('4', 'Foi a inalação ou algo que engoli e me fez mal'), ('5', 'Foi praticando alguma atividade física/exercício/esporte'), ('6', 'Foi um acidente que sofri quando estava trabalhando'), ('7', 'Foi um acidente enquanto andava de bicicleta'), ('8', 'Foi uma queda'), ('9', 'Foi outra causa')], max_length=2, null=True, verbose_name='127. Nos últimos 12 meses, qual foi a principal causa do ferimento ou da lesão mais séria que aconteceu com você?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_128',
            field=models.CharField(blank=True, choices=[('0', 'Não andei de bicicleta nos últimos 12 meses'), ('1', 'Andei de bicicleta e não sofri acidente'), ('2', 'Andei de bicicleta e sofri acidente')], max_length=2, null=True, verbose_name='128. Nos últimos 12 meses, você sofreu algum acidente de bicicleta (caiu e se machucou)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_129',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Sim'), ('1', 'Não')], max_length=2), blank=True, null=True, size=None, verbose_name='129. Alguma vez na vida você foi forçado(a) a ter relação sexual?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_13',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='13. Na sua casa tem empregado (a) doméstico (a)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_130',
            field=models.CharField(blank=True, choices=[('0', 'Namorado(a)/ex-namorado(a)'), ('1', 'Amigo(a)'), ('2', 'Pai/mãe/padrasto/madrasta'), ('3', 'Outros familiares'), ('4', 'Desconhecido(a)'), ('5', 'Outro (as)')], max_length=2, null=True, verbose_name='130. Quem forçou você a ter relação sexual?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_131',
            field=models.CharField(blank=True, choices=[('0', 'Muito bom'), ('1', 'Bom'), ('2', 'Regular'), ('3', 'Ruim'), ('4', 'Muito ruim')], max_length=2, null=True, verbose_name='131. Como você classificaria seu estado de saúde?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_132',
            field=models.CharField(blank=True, choices=[('0', 'Não faltei a escola nos últimos 12 meses por motivos de saúde'), ('1', '1 a 3 dias nos últimos 12 meses'), ('2', '4 a 7 dias nos últimos 12 meses'), ('3', '8 a 15 dias nos últimos 12 meses'), ('4', '16 dias ou mais nos últimos 12 meses')], max_length=2, null=True, verbose_name='132. Nos últimos 12 meses, quantos dias você faltou a escola por motivo(s) relacionado(s) à sua saúde?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_133',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='133. Nos últimos 12 meses você procurou algum serviço ou profissional de saúde para atendimento relacionado à própria saúde?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_134',
            field=models.CharField(blank=True, choices=[('0', 'Unidade Básica de Saúde (Centro ou Posto de saúde ou Unidade de Saúde da Família/PSF)'), ('1', 'Consultório médico particular ou clínica particular'), ('2', 'Consultório odontológico'), ('3', 'Consultório de outro profissional de saúde (fonoaudiólogo, psicólogo etc.)'), ('4', 'Serviço de especialidades médicas ou Policlínica'), ('5', 'Pronto-socorro, emergência ou UPA'), ('6', 'Hospital'), ('7', 'Laboratório ou clínica para exames complementares'), ('8', 'Serviço de atendimento domiciliar'), ('9', 'Farmácia'), ('10', 'Outro')], max_length=2, null=True, verbose_name='134. Nos últimos 12 meses, qual foi o serviço de saúde que você procurou com mais frequência?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_135',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não'), ('2', 'Não procurei uma Unidade Básica de Saúde')], max_length=2, null=True, verbose_name='135. Você foi atendido(a) na última vez que procurou alguma Unidade Básica de Saúde (Centro ou Posto de saúde ou Unidade de Saúde da Família/PSF), nestes últimos 12 meses?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_136',
            field=models.CharField(blank=True, choices=[('0', 'Apoio para controle de peso (ganhar ou perder)'), ('1', 'Apoio para parar de fumar'), ('2', 'Acidente ou lesão'), ('3', 'Reabilitação ou terapia'), ('4', 'Doença'), ('5', 'Problema odontológico'), ('6', 'Vacinação'), ('7', 'Consulta para métodos contraceptivos (preservativos, pílula, DIU etc.)'), ('8', 'Buscar contracepção de emergência (pílula do dia seguinte)'), ('9', 'Teste para HIV, Sífilis ou Hepatite B'), ('10', 'Pré-natal / Teste para gravidez'), ('11', 'Solicitação de atestado médico'), ('12', 'Outro')], max_length=2, null=True, verbose_name='136. Qual foi o principal motivo da sua procura na Unidade Básica de Saúde (Centro ou Posto de saúde ou Unidade de Saúde da Família/PSF) nesta última vez?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_137',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='137. Você conhece/ouviu falar sobre a campanha de vacinação contra o vírus HPV?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_138',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='138. Você foi vacinada contra o vírus HPV?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_139',
            field=models.CharField(blank=True, choices=[('0', 'Muito importante'), ('1', 'Importante'), ('2', 'Pouco importante'), ('3', 'Sem importância')], max_length=2, null=True, verbose_name='139. Você considera sua imagem corporal como sendo algo:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_14',
            field=models.CharField(blank=True, choices=[('0', '1 a 2 dias por semana'), ('1', '3 ou mais dias por semana.')], max_length=2, null=True, verbose_name='14. Caso responda SIM, quantos dias esta pessoa trabalha?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_140',
            field=models.CharField(blank=True, choices=[('0', 'Muito satisfeito(a)'), ('1', 'Satisfeito(a)'), ('2', 'Indiferente'), ('3', 'Insatisfeito(a)'), ('4', 'Muito insatisfeito(a)')], max_length=2, null=True, verbose_name='140. Como você se sente em relação ao seu corpo?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_141',
            field=models.CharField(blank=True, choices=[('0', 'Muito magro(a)'), ('1', 'Magro(a)'), ('2', 'Normal'), ('3', 'Gordo(a)'), ('4', 'Muito Gordo(a)')], max_length=2, null=True, verbose_name='141. Quanto ao seu corpo, você se considera:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_142',
            field=models.CharField(blank=True, choices=[('0', 'Não estou fazendo nada'), ('1', 'Estou tentando perder peso'), ('2', 'Estou tentando ganhar peso'), ('3', 'Estou tentando manter o mesmo peso')], max_length=2, null=True, verbose_name='142. O que você está fazendo em relação a seu peso?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_143',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='143. Nos últimos 30 dias, você vomitou ou tomou laxantes para perder peso ou evitar ganhar peso?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_144',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='144. Nos últimos 30 dias, você tomou algum remédio, fórmula ou outro produto para perder peso, sem acompanhamento médico?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_145',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='145. Nos últimos 30 dias, você tomou algum remédio, fórmula ou outro produto para ganhar peso ou massa muscular sem acompanhamento médico?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_146',
            field=models.CharField(blank=True, choices=[('0', 'Fácil'), ('1', 'Difícil'), ('2', 'Chato'), ('3', 'Legal'), ('4', 'Interessante'), ('5', 'Informativo'), ('6', 'Cansativo'), ('7', 'Constrangedor')], max_length=2, null=True, verbose_name='146. O que você achou deste questionário?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_15',
            field=models.CharField(blank=True, choices=[('0', 'Minha mãe não estudou'), ('1', 'Minha mãe começou o ensino fundamental ou 1o grau, mas não terminou'), ('2', 'Minha mãe terminou o ensino fundamental ou 1o grau'), ('3', 'Minha mãe começou o ensino médio ou 2o grau, mas não terminou'), ('4', 'Minha mãe terminou o ensino médio ou 2o grau'), ('5', 'Minha mãe começou a faculdade (ensino superior), mas não terminou'), ('6', 'Minha mãe terminou a faculdade (ensino superior)'), ('7', 'Não sei')], max_length=2, null=True, verbose_name='15. Qual nível de ensino (grau) sua mãe estudou ou estuda?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_16',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='16. Você tem algum trabalho, emprego ou negócio atualmente?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_17',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='17. Você recebe dinheiro por este trabalho, emprego ou negócio?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_18',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='18. Sua família recebe benefícios do Programa Bolsa Família? Comportamento Alimentar'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_19',
            field=models.CharField(blank=True, choices=[('0', 'Sim, todos os dias'), ('1', 'Sim, 5 a 6 dias por semana'), ('2', 'Sim, 3 a 4 dias por semana'), ('3', 'Sim, 1 a 2 dias por semana'), ('4', 'Raramente'), ('5', 'Não')], max_length=2, null=True, verbose_name='19. Você costuma tomar o café da manhã?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_2',
            field=models.CharField(blank=True, choices=[('0', 'Somente continuar estudando'), ('1', 'Somente trabalhar'), ('2', 'Continuar estudando e trabalhar'), ('3', 'Seguir outro plano'), ('4', 'Não sei')], max_length=2, null=True, verbose_name='02. Quando terminar o ciclo/curso que você está frequentando atualmente, você pretende?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_20',
            field=models.CharField(blank=True, choices=[('0', 'Sim, todos os dias'), ('1', 'Sim, 5 a 6 dias por semana'), ('2', 'Sim, 3 a 4 dias por semana'), ('3', 'Sim, 1 a 2 dias por semana'), ('4', 'Raramente'), ('5', 'Não')], max_length=2, null=True, verbose_name='20. Você costuma almoçar ou jantar com sua mãe, pai ou responsável?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_21',
            field=models.CharField(blank=True, choices=[('0', 'Sim, todos os dias'), ('1', 'Sim, 5 a 6 dias por semana'), ('2', 'Sim, 3 a 4 dias por semana'), ('3', 'Sim, 1 a 2 dias por semana'), ('4', 'Raramente'), ('5', 'Não')], max_length=2, null=True, verbose_name='21. Você costuma comer quando está assistindo à TV ou estudando?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_22',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não'), ('2', 'Não sei')], max_length=2, null=True, verbose_name='22. Sua escola oferece comida (merenda escolar/almoço) aos alunos da sua turma? (Não considerar lanches/comida comprados na cantina)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_23',
            field=models.CharField(blank=True, choices=[('0', 'Sim, todos os dias'), ('1', 'Sim, 3 a 4 dias por semana'), ('2', 'Sim, 1 a 2 dias por semana'), ('3', 'Raramente'), ('4', 'Não')], max_length=2, null=True, verbose_name='23. Você costuma comer a comida (merenda/almoço) oferecida pela escola? (Não considerar lanches/comida comprados na cantina)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_24',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maior parte das vezes'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='24. Nos últimos 30 dias, com que frequência você ficou com fome por não ter comida suficiente em sua casa?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_25',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='25. Leite de vaca:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_26',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='26. Leite de vaca com adição de achocolatados em pó (nescau, toddy, ovomaltine), mel ou açúcar:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_27',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='27. Achocolatados líquidos comprados em supermercados como, por exemplo: Todyynho, Chokinho; Nescau; Italac etc.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_28',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='28. Iogurte como, por exemplo: Danone, Danoninho, Nestlé, Ninho, etc.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_29',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='29. Queijo.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_3',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='03. Você mora com sua mãe?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_30',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='30. Sobremesas feitas com leite (pudim, flam, pudim de chocolate, creme de leite).'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_31',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='31. Gelados (Picolé, sorvete, geladinho).'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_32',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='32. Pão ou torrada (torrada é o mesmo que pão, sendo que em torrado).'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_33',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='33. Flocos de cereais açucarados (por exemplo, flocos conhecidos como sucrilhos ou equivalentes, nescau cereal), etc.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_34',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='34. Flocos de cereais (aveia, milho, centeio, como os da marca Nesfit e Nutry)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_35',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='35. Arroz, massas, batatas.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_36',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='36. Batatas fritas pacote Ruffles, Pringles, Lay’s'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_37',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='37. Batatas fritas caseiras.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_38',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='38. Bolachas Maria, bolachas Mabel, biscoitos ou bolachas cream cracker, (ou água e sal) etc.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_39',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='39. Outras bolachas (biscoitos recheados como Bono, Trakinas e Oreo).'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_4',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='04. Você mora com seu pai?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_40',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='40. Produtos de pastelaria (coxinhas, pastéis, salgadinhos de queijo, kibes).'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_41',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='41. Snacks (chocolates vendidos em barrinhas, como Twix, Kitkat, Bis e Chokito)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_42',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='42. Marmelada, doce em potinho, geleia, mel. (Como Paçoquita, Melzinho e Pé de moleque)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_43',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='43. Açúcares em geral.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_44',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='44. Sopas comuns caseiras (de carne, frango ou legumes)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_45',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='45. Vegetais crus em salada ou cozinhados (Cenoura, couve flor, brócolis, alface, beterraba, agrião)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_46',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='46. Leguminosas (feijão, grão de bico, ervilhas, favas).'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_47',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='47. Fruta fresca. (Manga, caju, banana, goiaba, acerola, murici, maça, laranja)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_48',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='48. Frutos enlatados em calda: (pêssego, banana, caju, goiaba).'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_49',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='49. Sucos naturais (de laranja, acerola, tangerina, uva)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_5',
            field=models.CharField(blank=True, choices=[('0', '1 pessoa (moro sozinho)'), ('1', '2 pessoas'), ('2', '3 pessoas'), ('3', '4 pessoas'), ('4', '5 pessoas'), ('5', '6 pessoas'), ('6', '7 pessoas'), ('7', '8 pessoas'), ('8', '9 pessoas'), ('9', '10 pessoas ou mais')], max_length=2, null=True, verbose_name='05. Contando com você, quantas pessoas moram na sua casa ou apartamento?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_50',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='50. Refrigerantes (Coca cola, graraná ou fanta) ou ainda sucos de caixinha com néctar (como Kapo, del Valle)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_51',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='51. Pizzas. (Mini Pizza por exemplo)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_52',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='52. Hamburguer e cachorro quente.'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_53',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='53. Rebuçados, gomas, pastilhas elásticas. (Chicletes, balinhas, jujubas)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_54',
            field=models.CharField(blank=True, choices=[('0', 'Nunca ou menos de uma vez por mês'), ('1', '1 a 3 vezes por mês'), ('2', '1 vez por semana'), ('3', '2 a 4 vezes por semana'), ('4', '6 a 8 vezes por semana'), ('5', '1 vez por dia'), ('6', '2 a 3 vezes por dia'), ('7', '4 a 6 vezes por dia'), ('8', 'Mais de 8 vezes por dia')], max_length=2, null=True, verbose_name='54. Rosquinhas (como Donuts, Sonhos, Rosquinhas de Polvilho, Pão de Mel) Hábitos Alimentares quando o (a) estudante tinha menos de dois anos de idade'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_55',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='55. Seu filho (a) foi alimentado (a) com leite materno?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_56',
            field=models.CharField(blank=True, choices=[('0', 'Não. Meu filho nunca foi alimentado apenas de leite materno'), ('1', 'Sim. Meu filho foi alimentado apenas de leite materno:'), ('2', 'Até um mês ou menos;'), ('3', 'Até 2 meses;'), ('4', 'Até 3 meses;'), ('5', 'Até 4 meses;'), ('6', 'Até 5 meses;'), ('7', 'Até 6 meses ou mais.')], max_length=2, null=True, verbose_name='56. Ele (a) mamou (apenas no peito) até quantos meses de idade?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_57',
            field=models.CharField(blank=True, choices=[('0', 'Até 6 meses de idade;'), ('1', 'Até 7 meses de idade;'), ('2', 'Até 8 meses de idade;'), ('3', 'Até 9 meses de idade;'), ('4', 'Até 10 meses de idade;'), ('5', 'Até 11 meses de idade;'), ('6', 'Até 12 meses de idade;'), ('7', 'Mais de 12 meses até 18 meses de idade;'), ('8', 'Mais de 18 meses até 24 meses de idade.')], max_length=2, null=True, verbose_name='57. Se seu filho ou sua filha mamou até seis meses ou mais, até quantos meses ele (a) mamou no peito (mesmo que tenha se alimentado com outras comidas ou bebidas) Meu (minha) Filho (filha) mamou no peito até:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_58',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='58. Antes de completar dois anos de idade, seu filho (a) foi alimentado (a) com leite industrial? (aquele leite comprado nas farmácias ou supermercados)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_59',
            field=models.CharField(blank=True, choices=[('0', 'Até um mês ou menos;'), ('1', 'Até 2 meses;'), ('2', 'Até 3 meses;'), ('3', 'Até 4 meses;'), ('4', 'Até 5 meses;'), ('5', 'Até 6 meses ou mais;'), ('6', 'Até 7 meses de idade;'), ('7', 'Até 8 meses de idade;'), ('8', 'Até 9 meses de idade;'), ('9', 'Até 10 meses de idade;'), ('10', 'Até 11 meses de idade;'), ('11', 'Até 12 meses de idade;'), ('12', 'Mais de 12 meses até 18 meses de idade;'), ('13', 'Mais de 18 meses até 24 meses de idade.')], max_length=2, null=True, verbose_name='59. Caso sua resposta tenha sido SIM, até quantos meses ele se alimentou de leite industrial, isto é, aquele leite que é comprado nas farmácias e supermercados?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_6',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='06. Na sua casa tem telefone fixo (convencional)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_60',
            field=models.CharField(blank=True, choices=[('0', 'Leite + papinhas'), ('1', 'Leite + sopas'), ('2', 'Leite + frutas')], max_length=2, null=True, verbose_name='60. Até dois anos de idade, seu filho ou sua filha recebeu alimentação mista, isto é:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_61',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='61. Até dois anos de idade, seu filho ou sua filha tomou leite de vaca?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_62',
            field=models.CharField(blank=True, choices=[('1', 'Menos de 1 mês'), ('2', '1 e menos de 2 meses;'), ('3', '2 e menos de 3 meses'), ('4', '3 e menos de 4 meses;'), ('5', '4 e menos de 5 meses;'), ('6', '5 e menos de 6 meses'), ('7', '6 e menos de 7 meses;'), ('8', '7 e menos de 8 meses;'), ('9', '8 e menos de 9 meses;'), ('10', '9 e menos de 10 meses'), ('11', '10 e menos de 11 meses;'), ('12', '11 e menos de 12 meses;'), ('13', '12 e menos de 18 meses de idade;'), ('14', '18 e menos 24 meses de idade.')], max_length=2, null=True, verbose_name='62. Caso sua resposta tenha sido sim, com que idade (em meses) ele começou a tomar leite de vaca?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_63',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 dia nos últimos 7 dias'), ('2', '2 dias nos últimos 7 dias'), ('3', '3 dias nos últimos 7 dias'), ('4', '4 dias nos últimos 7 dias'), ('5', '5 dias nos últimos 7 dias'), ('6', '5 dias mais sábado, nos últimos 7 dias'), ('7', '5 dias mais sábado e domingo, nos últimos 7 dias')], max_length=2, null=True, verbose_name='63. Nos últimos dias, em quantos deles você foi a pé ou de bicicleta para a escola?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_64',
            field=models.CharField(blank=True, choices=[('0', 'Menos de 10 minutos por dia'), ('1', '10 a 19 minutos por dia'), ('2', '20 a 29 minutos por dia'), ('3', '30 a 39 minutos por dia'), ('4', '40 a 49 minutos por dia'), ('5', '50 a 59 minutos por dia'), ('6', '1 hora ou mais por dia')], max_length=2, null=True, verbose_name='64. Quando você vai para a escola a pé ou de bicicleta, quanto tempo você gasta?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_65',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 dia nos últimos 7 dias'), ('2', '2 dias nos últimos 7 dias'), ('3', '3 dias nos últimos 7 dias'), ('4', '4 dias nos últimos 7 dias'), ('5', '5 dias nos últimos 7 dias'), ('6', '5 dias mais sábado, nos últimos 7 dias'), ('7', '5 dias mais sábado e domingo, nos últimos 7 dias')], max_length=2, null=True, verbose_name='66. Nos últimos sete dias, quanto tempo por dia você fez atividade física ou esporte durante as aulas de educação física na escola?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_66',
            field=models.CharField(blank=True, choices=[('0', 'Não fiz aula de educação física na escola nos últimos 7 dias.'), ('1', 'Menos de 10 minutos por dia'), ('2', '10 a 19 minutos por dia'), ('3', '20 a 29 minutos por dia'), ('4', '30 a 39 minutos por dia'), ('5', '40 a 49 minutos por dia'), ('6', '50 a 59 minutos por dia'), ('7', '1 hora ou mais por dia')], max_length=2, null=True, verbose_name='67. Nos últimos 7 dias, sem contar as aulas de educação física da escola, em quantos dias você praticou alguma atividade física, como esportes, dança, ginástica, musculação, lutas ou outra atividade?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_67',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 dia nos últimos 7 dias'), ('2', '2 dias nos últimos 7 dias'), ('3', '3 dias nos últimos 7 dias'), ('4', '4 dias nos últimos 7 dias'), ('5', '5 dias nos últimos 7 dias'), ('6', '5 dias mais sábado, nos últimos 7 dias'), ('7', '5 dias mais sábado e domingo, nos últimos 7 dias')], max_length=2, null=True, verbose_name='68. Normalmente, quanto tempo por dia duram essas atividades (como esportes, dança, ginástica, musculação, lutas ou outra atividade) que você faz? (Sem contar as aulas de educação física)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_68',
            field=models.CharField(blank=True, choices=[('0', 'Menos de 10 minutos por dia'), ('1', '10 a 19 minutos por dia'), ('2', '20 a 29 minutos por dia'), ('3', '30 a 39 minutos por dia'), ('4', '40 a 49 minutos por dia'), ('5', '50 a 59 minutos por dia'), ('6', '1 hora ou mais por dia')], max_length=2, null=True, verbose_name='69. Nos últimos 7 dias, em quantos dias você fez atividade física por pelo menos 60 minutos (1 hora) por dia? (Some todo o tempo que você gastou em qualquer tipo de atividade física, em cada dia)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_7',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Sim'), ('1', 'Não')], max_length=2), blank=True, null=True, size=None, verbose_name='07. Você tem celular?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_70',
            field=models.CharField(blank=True, choices=[('0', 'Não faria mesmo assim'), ('1', 'Faria atividade física em alguns dias da semana'), ('2', 'Faria atividade física na maioria dos dias da semana'), ('3', 'Já faço atividade física em alguns dias da semana'), ('4', 'Já faço atividade física na maioria dos dias da semana')], max_length=2, null=True, verbose_name='71. Em um dia de semana comum, quantas horas por dia você assiste a TV? (não contar sábado, domingo e feriado)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_71',
            field=models.CharField(blank=True, choices=[('0', 'Não assisto a TV'), ('1', 'Até 1 hora por dia'), ('2', 'Mais de 1 hora até 2 horas por dia'), ('3', 'Mais de 2 horas até 3 horas por dia'), ('4', 'Mais de 3 horas até 4 horas por dia'), ('5', 'Mais de 4 horas até 5 horas por dia'), ('6', 'Mais de 5 horas até 6 horas por dia'), ('7', 'Mais de 6 horas até 7 horas por dia'), ('8', 'Mais de 7 horas até 8 horas por dia'), ('9', 'Mais de 8 horas por dia')], max_length=2, null=True, verbose_name='72. Em um dia de semana comum, quanto tempo você fica sentado(a), assistindo televisão, usando computador, jogando videogame, conversando com amigos(as) ou fazendo outras atividades sentado(a)? (não contar sábado, domingo, feriados e o tempo sentado na escola)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_72',
            field=models.CharField(blank=True, choices=[('0', 'Até 1 hora por dia'), ('1', 'Mais de 1 hora até 2 horas por dia'), ('2', 'Mais de 2 horas até 3 horas por dia'), ('3', 'Mais de 3 horas até 4 horas por dia'), ('4', 'Mais de 4 horas até 5 horas por dia'), ('5', 'Mais de 5 horas até 6 horas por dia'), ('6', 'Mais de 6 horas até 7 horas por dia'), ('7', 'Mais de 7 horas até 8 horas por dia'), ('8', 'Mais de 8 horas por dia')], max_length=2, null=True, verbose_name='73. Alguma vez na vida, você já fumou cigarro, mesmo uma ou duas tragadas?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_73',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='74. Que idade você tinha quando experimentou fumar cigarro pela primeira vez?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_74',
            field=models.CharField(blank=True, choices=[('0', '7 anos de idade ou menos'), ('1', '8 anos'), ('2', '9 anos'), ('3', '10 anos'), ('4', '11 anos'), ('5', '12 anos'), ('6', '13 anos'), ('7', '14 anos'), ('8', '15 anos'), ('9', '16 anos'), ('10', '17 anos'), ('11', '18 anos ou mais')], max_length=2, null=True, verbose_name='75. Nos últimos 30 dias, em quantos dias você fumou cigarros?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_75',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 30 dias'), ('2', '3 a 5 dias nos últimos 30 dias'), ('3', '6 a 9 dias nos últimos 30 dias'), ('4', '10 a 19 dias nos últimos 30 dias'), ('5', '20 a 29 dias nos últimos 30 dias'), ('6', 'Todos os dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='76. Nos últimos 30 dias, em geral, como você conseguiu seus próprios cigarros?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_76',
            field=models.CharField(blank=True, choices=[('0', 'Não fumei cigarros nos últimos 30 dias'), ('1', 'Eu os comprei numa loja ou botequim'), ('2', 'Eu os comprei num vendedor ambulante (camelô)'), ('3', 'Dei dinheiro para alguém comprá-los para mim'), ('4', 'Eu os pedi a alguém'), ('5', 'Eu peguei escondido'), ('6', 'Uma pessoa mais velha me deu'), ('7', 'Eu os consegui de outro modo')], max_length=2, null=True, verbose_name='77. Nos ultimos 30 dias, alguém se recusou a lhe vender cigarros por causa de sua idade?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_77',
            field=models.CharField(blank=True, choices=[('0', 'Não tentei comprar cigarros nos últimos 30 dias;'), ('1', 'Sim, alguém se recusou a me vender cigarros por causa de minha idade;'), ('2', 'Não, minha idade não me impediu de comprar cigarros.')], max_length=2, null=True, verbose_name='78. Nos últimos 30 dias, em quantos dias você usou outros produtos de tabaco: cigarros de palha ou enrolados a mão, charuto, cachimbo, cigarrilha, cigarro indiano ou bali, narguilé, rapé, fumo de mascar etc.? (não incluir cigarro comum)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_78',
            field=models.CharField(blank=True, choices=[('0', 'Não uso outros produtos de tabaco'), ('1', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('2', '1 ou 2 dias nos últimos 30 dias'), ('3', '3 a 5 dias nos últimos 30 dias'), ('4', '6 a 9 dias nos últimos 30 dias'), ('5', '10 a 19 dias nos últimos 30 dias'), ('6', '20 a 29 dias nos últimos 30 dias'), ('7', 'Todos os 30 dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='79. Qual outro produto do tabaco você usou com mais frequência nos últimos 30 dias?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_79',
            field=models.CharField(blank=True, choices=[('0', 'Não usei nenhum produto do tabaco (os produtos do tabaco estão abaixo relacionados)'), ('1', 'Cigarros de cravo (conhecidos como cigarros de Bali).'), ('2', 'Cigarros enrolados à mão (conhecidos como cigarros de palha ou papel)'), ('3', 'Cigarrilhas'), ('4', 'Charutos, charutos pequenos.'), ('5', 'Fumo para mascar'), ('6', 'Narguilé (cachimbo de água)'), ('7', 'Cigarros indianos (bidis)'), ('8', 'Cigarro eletrônico (e-cigarette)'), ('9', 'Outros')], max_length=2, null=True, verbose_name='80. Nos últimos 7 dias, em quantos dias pessoas fumaram na sua presença?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_8',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='08. Na sua casa tem computador (de mesa, notbook, laptop etc.)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_80',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 7 dias'), ('2', '3 ou 4 dias nos últimos 7 dias'), ('3', '5 ou 6 dias nos últimos 7 dias'), ('4', 'Todos os 7 dias')], max_length=2, null=True, verbose_name='81. Algum de seus pais ou responsáveis fuma?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_81',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum deles'), ('1', 'Só meu pai ou responsável do sexo masculino'), ('2', 'Só minha mãe ou responsável do sexo feminino'), ('3', 'Meu pai e minha mãe ou responsáveis'), ('4', 'Não sei')], max_length=2, null=True, verbose_name='82. Alguma vez na vida você tomou uma dose de bebida alcoólica (uma dose equivale a uma'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_82',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='lata de cerveja ou uma taça de vinho ou uma dose de cachaça ou uísque etc.)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_83',
            field=models.CharField(blank=True, choices=[('0', '7 anos de idade ou menos'), ('1', '8 anos'), ('2', '9 anos'), ('3', '10 anos'), ('4', '11 anos'), ('5', '12 anos'), ('6', '13 anos'), ('7', '14 anos'), ('8', '15 anos'), ('9', '16 anos'), ('10', '17 anos'), ('11', '18 anos ou mais')], max_length=2, null=True, verbose_name='83. Que idade você tinha quando tomou a primeira dose de bebida alcoólica (uma dose equivale a uma lata de cerveja ou uma taça de vinho ou uma dose de cachaça ou uísque etc.)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_84',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 30 dias'), ('2', '3 a 5 dias nos últimos 30 dias'), ('3', '6 a 9 dias nos últimos 30 dias'), ('4', '10 a 19 dias nos últimos 30 dias'), ('5', '20 a 29 dias nos últimos 30 dias'), ('6', 'Todos os dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='84. Nos últimos 30 dias, em quantos dias você tomou pelo menos um copo ou uma dose de bebida alcoólica (uma dose equivale a uma lata de cerveja ou uma taça de vinho ou uma dose de cachaça ou uísque etc.)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_85',
            field=models.CharField(blank=True, choices=[('0', 'Não tomei nenhuma bebida alcoólica nos últimos 30 dias (0 dia)'), ('1', 'Menos de um copo ou dose nos últimos 30 dias'), ('2', '1 copo ou 1 dose nos últimos 30 dias'), ('3', '2 copos ou 2 doses nos últimos 30 dias'), ('4', '3 copos ou 3 doses nos últimos 30 dias'), ('5', '4 copos ou 4 doses nos últimos 30 dias'), ('6', '5 copos ou mais ou 5 doses ou mais nos últimos 30 dias')], max_length=2, null=True, verbose_name='85. Nos últimos 30 dias, nos dias em que você tomou alguma bebida alcoólica, quantos copos ou doses você tomou por dia?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_86',
            field=models.CharField(blank=True, choices=[('0', 'Não tomei nenhuma bebida alcoólica nos últimos 30 dias (0 dia)'), ('1', 'Comprei no mercado, loja, bar ou supermercado'), ('2', 'Comprei de um vendedor de rua'), ('3', 'Dei dinheiro a alguém que comprou para mim'), ('4', 'Consegui com meus amigos'), ('5', 'Peguei na minha casa sem permissão'), ('6', 'Consegui com alguém em minha família'), ('7', 'Em uma festa'), ('8', 'Consegui de outro modo')], max_length=2, null=True, verbose_name='86. Nos últimos 30 dias, na maioria das vezes, como você conseguiu a bebida que tomou?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_87',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez na vida (0 vez)'), ('1', '1 ou 2 vezes na vida'), ('2', '3 a 5 vezes na vida'), ('3', '6 a 9 vezes na vida'), ('4', '10 ou mais vezes na vida')], max_length=2, null=True, verbose_name='87. Na sua vida, quantas vezes você bebeu tanto que ficou realmente bêbado(a)?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_88',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma vez na vida (0 vez)'), ('1', '1 ou 2 vezes na vida'), ('2', '3 a 5 vezes na vida'), ('3', '6 a 9 vezes na vida'), ('4', '10 ou mais vezes na vida')], max_length=2, null=True, verbose_name='88. Na sua vida, quantas vezes você teve problemas com sua família ou amigos, perdeu aulas ou brigou por que tinha bebido?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_89',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', 'Poucos'), ('2', 'Alguns'), ('3', 'A maioria'), ('4', 'Todos'), ('5', 'Não sei')], max_length=2, null=True, verbose_name='89. Quantos amigos seus consomem bebida alcoólica?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_9',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='09. Você tem acesso à internet em sua casa?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_90',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='90. Alguma vez na vida, você já usou alguma droga como: maconha, cocaína, crack, cola, loló, lança-perfume, ecstasy, oxy etc.?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_91',
            field=models.CharField(blank=True, choices=[('0', '7 anos ou menos'), ('1', '8 anos'), ('2', '9 anos'), ('3', '10 anos'), ('4', '11 anos'), ('5', '12 anos'), ('6', '13 anos'), ('7', '14 anos'), ('8', '15 anos'), ('9', '16 anos'), ('10', '17 anos'), ('11', '18 anos ou mais')], max_length=2, null=True, verbose_name='91. Que idade você tinha quando usou alguma droga como: maconha, cocaína, crack, cola, loló, lança-perfume, ecstasy, oxy ou outra pela primeira vez?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_92',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 30 dias'), ('2', '3 a 5 dias nos últimos 30 dias'), ('3', '6 a 9 dias nos últimos 30 dias'), ('4', '10 ou mais dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='92. Nos ultimos 30 dias, quantos dias você usou droga como maconha, cocaína, crack, cola, loló, lança-perfume, ecstasy, oxy etc.?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_93',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 30 dias'), ('2', '3 a 5 dias nos últimos 30 dias'), ('3', '6 a 9 dias nos últimos 30 dias'), ('4', '10 ou mais dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='93. Nos últimos 30 dias, quantos dias você usou maconha?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_94',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 30 dias'), ('2', '3 a 5 dias nos últimos 30 dias'), ('3', '6 a 9 dias nos últimos 30 dias'), ('4', '10 ou mais dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='94. Nos últimos 30 dias, quantos dias você usou crack?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_95',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', 'Poucos'), ('2', 'Alguns'), ('3', 'A maioria'), ('4', 'Todos'), ('5', 'Não sei')], max_length=2, null=True, verbose_name='95. Quantos amigos seus usam drogas?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_96',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 30 dias'), ('2', '3 a 5 dias nos últimos 30 dias'), ('3', '6 a 9 dias nos últimos 30 dias'), ('4', '10 ou mais dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='96. Nos últimos 30 dias, em quantos dias você faltou às aulas ou à escola sem permissão dos seus pais ou responsáveis?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_97',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maior parte do tempo'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='97. Nos últimos 30 dias, com que frequência seus pais ou responsáveis sabiam realmente o que você estava fazendo em seu tempo livre?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_98',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maior parte do tempo'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='98. Nos últimos 30 dias, com que frequência seus pais ou responsáveis verificaram se os seus deveres de casa (lição de casa) foram feitos?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_99',
            field=models.CharField(blank=True, choices=[('0', 'Nunca'), ('1', 'Raramente'), ('2', 'Às vezes'), ('3', 'Na maior parte do tempo'), ('4', 'Sempre')], max_length=2, null=True, verbose_name='99. Nos últimos 30 dias, com que frequência seus pais ou responsáveis entenderam seus problemas e preocupações?'),
        ),
    ]
