# Generated by Django 2.1.3 on 2018-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0012_remove_aluno_numero_identificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero_identificacao',
            field=models.CharField(default=1, max_length=200, verbose_name='Número de identificação'),
            preserve_default=False,
        ),
    ]
