# Generated by Django 2.1.3 on 2018-11-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0013_aluno_numero_identificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=2, verbose_name='Turma'),
        ),
    ]
