# Generated by Django 2.1.3 on 2018-11-15 02:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0014_auto_20181112_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_11',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_12',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_13',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_14',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_15',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_16',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_17',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_18',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_21',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_22',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_23',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_24',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_25',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_26',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_27',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_28',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_31',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_32',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_33',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_34',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_35',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_36',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_37',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_38',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_41',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_42',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_43',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_44',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_45',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_46',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_47',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='carie_raiz_48',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='edentulismo_necessidade_inferior',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='edentulismo_necessidade_superior',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='edentulismo_uso_inferior',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='edentulismo_uso_superior',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='fluorose_valor',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='periodontal_pip_11',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='periodontal_pip_1716',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='periodontal_pip_2627',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='periodontal_pip_31',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='periodontal_pip_3736',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='periodontal_pip_4647',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_11',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_12',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_21',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_22',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_31',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_32',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_41',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='traumatismo_dente_42',
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(choices=[('Escola municipal Antônio Carlos Jobim', 'Escola municipal Antônio Carlos Jobim'), ('Escola municipal Antônio G. de Carvalho Filho', 'Escola municipal Antônio G. de Carvalho Filho'), ('Escola municipal Anne Frank', 'Escola municipal Anne Frank'), ('Escola municipal Darcy Ribeiro', 'Escola municipal Darcy Ribeiro'), ('Escola municipal Henrique Talone Pinheiro', 'Escola municipal Henrique Talone Pinheiro'), ('Escola municipal de T.I. Vinícius de Moraes', 'Escola municipal de T.I. Vinícius de Moraes'), ('Escola municipal Beatriz Rodrigues da Silva', 'Escola municipal Beatriz Rodrigues da Silva'), ('Escola municipal Mestre Pacífico S. Campos', 'Escola municipal Mestre Pacífico S. Campos'), ('Escola municipal Luiz Gonzaga', 'Escola municipal Luiz Gonzaga'), ('Escola municipal de T.I. Padre Josimo M. Tavares', 'Escola municipal de T.I. Padre Josimo M. Tavares'), ('Escola municipal de T.I. Daniel Batista', 'Escola municipal de T.I. Daniel Batista'), ('Escola municipal de T.I. Monsenhor Pedro P. Piagem', 'Escola municipal de T.I. Monsenhor Pedro P. Piagem'), ('Escola municipal Jorge Amado', 'Escola municipal Jorge Amado'), ('Escola municipal Maria Rosa de Castro Sales', 'Escola municipal Maria Rosa de Castro Sales'), ('Escola municipal Professor Sávia F. Jacome', 'Escola municipal Professor Sávia F. Jacome'), ('Escola municipal de T.I. Caroline C. C. da Silva', 'Escola municipal de T.I. Caroline C. C. da Silva'), ('Escola municipal Aurélio Buarque de Holanda', 'Escola municipal Aurélio Buarque de Holanda'), ('Escola municipal Maria Júlia Amorim Rodrigues', 'Escola municipal Maria Júlia Amorim Rodrigues'), ('Escola municipal Thiago Barbosa', 'Escola municipal Thiago Barbosa'), ('Escola municipal de T.I. Euridice F. de Mello', 'Escola municipal de T.I. Euridice F. de Mello'), ('Escola municipal de T.I. Margarida Gonçalves', 'Escola municipal de T.I. Margarida Gonçalves'), ('Escola municipal Crispim Pereira de Alencar', 'Escola municipal Crispim Pereira de Alencar'), ('Escola municipal de T.I. Aprigio T. de Matos', 'Escola municipal de T.I. Aprigio T. de Matos'), ('Escola municipal de T.I. João Beltrão', 'Escola municipal de T.I. João Beltrão'), ('Escola municipal de T.I. Luiz Nunes de Oliveira', 'Escola municipal de T.I. Luiz Nunes de Oliveira'), ('Escola municipal de T.I. Sueli Pereira A. Reche', 'Escola municipal de T.I. Sueli Pereira A. Reche'), ('Escola Silverio Ribeiro Matos (Mumbuca)', 'Escola Silverio Ribeiro Matos (Mumbuca)'), ('Escola de teste', 'Escola de teste')], max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_11',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_12',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 12'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_13',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 13'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_14',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 14'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_15',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 15'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_16',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_17',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 17'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_18',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 18'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_21',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 21'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_22',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 22'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_23',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 23'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_24',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 24'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_25',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 25'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_26',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 26'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_27',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_28',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 28'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_31',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_32',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 32'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_33',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 33'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_34',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 34'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_35',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 35'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_36',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_37',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 37'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_38',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 38'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_41',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 41'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_42',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 42'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_43',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 43'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_44',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 44'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_45',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 45'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_46',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 46'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_47',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_48',
            field=models.CharField(choices=[('A', 'A - Hígido'), ('B', 'B - Cariado'), ('C', 'C - Restaurado mas com cárie'), ('D', 'D - Restaurado e sem cárie'), ('E', 'E - Perdido devido à cárie'), ('F', 'F - Perdido por outras razões'), ('G', 'G - Apresenta selante'), ('H', 'H - Apoio de ponte ou coroa'), ('K', 'K - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('L', 'L - Dente excluído'), ('0', '0 - Hígido'), ('1', '1 - Cariado'), ('2', '2 - Restaurado mas com cárie'), ('3', '3 - Restaurado e sem cárie'), ('4', '4 - Perdido devido à cárie'), ('5', '5 - Perdido por outras razões'), ('6', '6 - Apresenta selante'), ('7', '7 - Apoio de ponte ou coroa'), ('8', '8 - Não erupcionado - raiz não exposta'), ('T', 'T - Trauma (fratura)'), ('9', '9 - Dente excluído')], max_length=2, null=True, verbose_name='Coroa 48'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_11',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_12',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 12'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_13',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 13'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_14',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 14'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_15',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 15'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_16',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_17',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 17'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_18',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 18'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_21',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 21'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_22',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 22'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_23',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 23'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_24',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 24'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_25',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 25'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_26',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 26'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_27',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_28',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 28'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_31',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_32',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 32'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_33',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 33'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_34',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 34'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_35',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 35'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_36',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_37',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 37'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_38',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 38'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_41',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 41'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_42',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 42'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_43',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 43'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_44',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 44'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_45',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 45'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_46',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 46'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_47',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_48',
            field=models.CharField(choices=[('0', '0 - Nenhum'), ('1', '1 - Restauração de 1 superfície'), ('2', '2 - Restauração de 2 ou mais superfícies'), ('3', '3 - Coroa por qualquer razão'), ('4', '4 - Faceta estética'), ('5', '5 - Tratamento pulpar e restauração'), ('6', '6 - Extração'), ('7', '7 - Remineralização de mancha branca'), ('8', '8 - Selante'), ('9', '9 - Sem informação')], max_length=2, null=True, verbose_name='Tratamento 48'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_55',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não (neste caso, pule para a questão 58)')], max_length=2, null=True, verbose_name='55. Seu filho (a) foi alimentado (a) com leite materno?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_56',
            field=models.CharField(blank=True, choices=[('0', 'Até um mês ou menos'), ('1', 'Até 2 meses;'), ('2', 'Até 3 meses;'), ('3', 'Até 4 meses;'), ('4', 'Até 5 meses;'), ('5', 'Até 6 meses ou mais.')], max_length=2, null=True, verbose_name='56. Ele (a) mamou (apenas no peito) até quantos meses de idade?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_57',
            field=models.CharField(blank=True, choices=[('0', 'Não. Meu filho ou filha não mamou até 6 meses ou mais'), ('1', 'Até 6 meses de idade;'), ('2', 'Até 7 meses de idade;'), ('3', 'Até 8 meses de idade;'), ('4', 'Até 9 meses de idade;'), ('5', 'Até 10 meses de idade;'), ('6', 'Até 11 meses de idade;'), ('7', 'Até 12 meses de idade;'), ('8', 'Mais de 12 meses até 18 meses de idade;'), ('9', 'Mais de 18 meses até 24 meses de idade.')], max_length=2, null=True, verbose_name='57. Se seu filho ou sua filha mamou até seis meses ou mais, até quantos meses ele (a) mamou no peito (mesmo que tenha se alimentado com outras comidas ou bebidas) Meu (minha) Filho (filha) mamou no peito até:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_60',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Não. Meu filho ou filha não recebeu alimentação mista até os dois anos de idade'), ('1', 'Sim. Leite + papinhas'), ('2', 'Sim. Leite + sopas'), ('3', 'Sim. Leite + frutas')], max_length=2), blank=True, null=True, size=None, verbose_name='60. Até dois anos de idade, seu filho ou sua filha recebeu alimentação mista, isto é:'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_62',
            field=models.CharField(blank=True, choices=[('0', 'Menos de 1 mês'), ('1', '1 e menos de 2 meses;'), ('2', '2 e menos de 3 meses'), ('3', '3 e menos de 4 meses;'), ('4', '4 e menos de 5 meses;'), ('5', '5 e menos de 6 meses'), ('6', '6 e menos de 7 meses;'), ('7', '7 e menos de 8 meses;'), ('8', '8 e menos de 9 meses;'), ('9', '9 e menos de 10 meses'), ('10', '10 e menos de 11 meses;'), ('11', '11 e menos de 12 meses;'), ('12', '12 e menos de 18 meses de idade;'), ('13', '18 e menos 24 meses de idade.')], max_length=2, null=True, verbose_name='62. Caso sua resposta tenha sido sim, com que idade (em meses) ele começou a tomar leite de vaca?'),
        ),
    ]
