# Generated by Django 2.1.3 on 2018-11-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0015_auto_20181114_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='raça',
            new_name='raca',
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='11: Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='17/16: Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='26/27: Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='31: Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='37/36: Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='46/47: Bolsa periodontal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='11: Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='17/16: Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='26/27: Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='31: Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='37/36: Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='46/47: Cálculo dentário'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='11: Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='17/16: Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='26/27: Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='31: Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='37/36: Sangramento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='46/47: Sangramento'),
        ),
    ]
