# Generated by Django 2.1.3 on 2018-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0016_auto_20181115_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=200, verbose_name='Turma'),
        ),
    ]
