# Generated by Django 2.1.3 on 2018-11-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0017_auto_20181115_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal 17/16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal 26/27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal 37/36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença de bolsa rasa'), ('2', '2 - Presença de bolsa profunda'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Bolsa periodontal 46/47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário 17/16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário 26/27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário 37/36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Cálculo dentário 46/47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_11',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_1716',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento 17/16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_2627',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento 26/27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_31',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_3736',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento 37/36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_4647',
            field=models.CharField(choices=[('0', '0 - Ausência'), ('1', '1 - Presença'), ('X', 'X - Sextante excluído'), ('9', '9 - Não examinado')], max_length=2, null=True, verbose_name='Sangramento 46/47'),
        ),
    ]
