# Generated by Django 2.1.3 on 2018-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0018_auto_20181115_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='questao_65',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 dia nos últimos 7 dias'), ('2', '2 dias nos últimos 7 dias'), ('3', '3 dias nos últimos 7 dias'), ('4', '4 dias nos últimos 7 dias'), ('5', '5 dias nos últimos 7 dias'), ('6', '5 dias mais sábado, nos últimos 7 dias'), ('7', '5 dias mais sábado e domingo, nos últimos 7 dias')], max_length=2, null=True, verbose_name='65. Nos últimos 7 dias, quantos dias você teve aulas de educação física na escola?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_66',
            field=models.CharField(blank=True, choices=[('0', 'Não fiz aula de educação física na escola nos últimos 7 dias.'), ('1', 'Menos de 10 minutos por dia'), ('2', '10 a 19 minutos por dia'), ('3', '20 a 29 minutos por dia'), ('4', '30 a 39 minutos por dia'), ('5', '40 a 49 minutos por dia'), ('6', '50 a 59 minutos por dia'), ('7', '1 hora ou mais por dia')], max_length=2, null=True, verbose_name='66. Nos últimos sete dias, quanto tempo por dia você fez atividade física ou esporte durante as aulas de educação física na escola?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_67',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 dia nos últimos 7 dias'), ('2', '2 dias nos últimos 7 dias'), ('3', '3 dias nos últimos 7 dias'), ('4', '4 dias nos últimos 7 dias'), ('5', '5 dias nos últimos 7 dias'), ('6', '5 dias mais sábado, nos últimos 7 dias'), ('7', '5 dias mais sábado e domingo, nos últimos 7 dias')], max_length=2, null=True, verbose_name='67. Nos últimos 7 dias, sem contar as aulas de educação física da escola, em quantos dias você praticou alguma atividade física, como esportes, dança, ginástica, musculação, lutas ou outra atividade?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_68',
            field=models.CharField(blank=True, choices=[('0', 'Menos de 10 minutos por dia'), ('1', '10 a 19 minutos por dia'), ('2', '20 a 29 minutos por dia'), ('3', '30 a 39 minutos por dia'), ('4', '40 a 49 minutos por dia'), ('5', '50 a 59 minutos por dia'), ('6', '1 hora ou mais por dia')], max_length=2, null=True, verbose_name='68. Normalmente, quanto tempo por dia duram essas atividades (como esportes, dança, ginástica, musculação, lutas ou outra atividade) que você faz? (Sem contar as aulas de educação física)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_70',
            field=models.CharField(blank=True, choices=[('0', 'Não faria mesmo assim'), ('1', 'Faria atividade física em alguns dias da semana'), ('2', 'Faria atividade física na maioria dos dias da semana'), ('3', 'Já faço atividade física em alguns dias da semana'), ('4', 'Já faço atividade física na maioria dos dias da semana')], max_length=2, null=True, verbose_name='70. Se você tivesse oportunidade de fazer atividade física na maioria dos dias da semana, qual seria a sua atitude?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_71',
            field=models.CharField(blank=True, choices=[('0', 'Não assisto a TV'), ('1', 'Até 1 hora por dia'), ('2', 'Mais de 1 hora até 2 horas por dia'), ('3', 'Mais de 2 horas até 3 horas por dia'), ('4', 'Mais de 3 horas até 4 horas por dia'), ('5', 'Mais de 4 horas até 5 horas por dia'), ('6', 'Mais de 5 horas até 6 horas por dia'), ('7', 'Mais de 6 horas até 7 horas por dia'), ('8', 'Mais de 7 horas até 8 horas por dia'), ('9', 'Mais de 8 horas por dia')], max_length=2, null=True, verbose_name='71. Em um dia de semana comum, quantas horas por dia você assiste a TV? (não contar sábado, domingo e feriado)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_72',
            field=models.CharField(blank=True, choices=[('0', 'Até 1 hora por dia'), ('1', 'Mais de 1 hora até 2 horas por dia'), ('2', 'Mais de 2 horas até 3 horas por dia'), ('3', 'Mais de 3 horas até 4 horas por dia'), ('4', 'Mais de 4 horas até 5 horas por dia'), ('5', 'Mais de 5 horas até 6 horas por dia'), ('6', 'Mais de 6 horas até 7 horas por dia'), ('7', 'Mais de 7 horas até 8 horas por dia'), ('8', 'Mais de 8 horas por dia')], max_length=2, null=True, verbose_name='72. Em um dia de semana comum, quanto tempo você fica sentado(a), assistindo televisão, usando computador, jogando videogame, conversando com amigos(as) ou fazendo outras atividades sentado(a)? (não contar sábado, domingo, feriados e o tempo sentado na escola)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_73',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='73. Alguma vez na vida, você já fumou cigarro, mesmo uma ou duas tragadas?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_74',
            field=models.CharField(blank=True, choices=[('0', '7 anos de idade ou menos'), ('1', '8 anos'), ('2', '9 anos'), ('3', '10 anos'), ('4', '11 anos'), ('5', '12 anos'), ('6', '13 anos'), ('7', '14 anos'), ('8', '15 anos'), ('9', '16 anos'), ('10', '17 anos'), ('11', '18 anos ou mais')], max_length=2, null=True, verbose_name='74. Que idade você tinha quando experimentou fumar cigarro pela primeira vez?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_75',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 30 dias'), ('2', '3 a 5 dias nos últimos 30 dias'), ('3', '6 a 9 dias nos últimos 30 dias'), ('4', '10 a 19 dias nos últimos 30 dias'), ('5', '20 a 29 dias nos últimos 30 dias'), ('6', 'Todos os dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='75. Nos últimos 30 dias, em quantos dias você fumou cigarros?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_76',
            field=models.CharField(blank=True, choices=[('0', 'Não fumei cigarros nos últimos 30 dias'), ('1', 'Eu os comprei numa loja ou botequim'), ('2', 'Eu os comprei num vendedor ambulante (camelô)'), ('3', 'Dei dinheiro para alguém comprá-los para mim'), ('4', 'Eu os pedi a alguém'), ('5', 'Eu peguei escondido'), ('6', 'Uma pessoa mais velha me deu'), ('7', 'Eu os consegui de outro modo')], max_length=2, null=True, verbose_name='76. Nos últimos 30 dias, em geral, como você conseguiu seus próprios cigarros?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_77',
            field=models.CharField(blank=True, choices=[('0', 'Não tentei comprar cigarros nos últimos 30 dias;'), ('1', 'Sim, alguém se recusou a me vender cigarros por causa de minha idade;'), ('2', 'Não, minha idade não me impediu de comprar cigarros.')], max_length=2, null=True, verbose_name='77. Nos ultimos 30 dias, alguém se recusou a lhe vender cigarros por causa de sua idade?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_78',
            field=models.CharField(blank=True, choices=[('0', 'Não uso outros produtos de tabaco'), ('1', 'Nenhum dia nos últimos 30 dias (0 dia)'), ('2', '1 ou 2 dias nos últimos 30 dias'), ('3', '3 a 5 dias nos últimos 30 dias'), ('4', '6 a 9 dias nos últimos 30 dias'), ('5', '10 a 19 dias nos últimos 30 dias'), ('6', '20 a 29 dias nos últimos 30 dias'), ('7', 'Todos os 30 dias nos últimos 30 dias')], max_length=2, null=True, verbose_name='78. Nos últimos 30 dias, em quantos dias você usou outros produtos de tabaco: cigarros de palha ou enrolados a mão, charuto, cachimbo, cigarrilha, cigarro indiano ou bali, narguilé, rapé, fumo de mascar etc.? (não incluir cigarro comum)'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_79',
            field=models.CharField(blank=True, choices=[('0', 'Não usei nenhum produto do tabaco (os produtos do tabaco estão abaixo relacionados)'), ('1', 'Cigarros de cravo (conhecidos como cigarros de Bali).'), ('2', 'Cigarros enrolados à mão (conhecidos como cigarros de palha ou papel)'), ('3', 'Cigarrilhas'), ('4', 'Charutos, charutos pequenos.'), ('5', 'Fumo para mascar'), ('6', 'Narguilé (cachimbo de água)'), ('7', 'Cigarros indianos (bidis)'), ('8', 'Cigarro eletrônico (e-cigarette)'), ('9', 'Outros')], max_length=2, null=True, verbose_name='79. Qual outro produto do tabaco você usou com mais frequência nos últimos 30 dias?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_80',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 ou 2 dias nos últimos 7 dias'), ('2', '3 ou 4 dias nos últimos 7 dias'), ('3', '5 ou 6 dias nos últimos 7 dias'), ('4', 'Todos os 7 dias')], max_length=2, null=True, verbose_name='80. Nos últimos 7 dias, em quantos dias pessoas fumaram na sua presença?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_81',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum deles'), ('1', 'Só meu pai ou responsável do sexo masculino'), ('2', 'Só minha mãe ou responsável do sexo feminino'), ('3', 'Meu pai e minha mãe ou responsáveis'), ('4', 'Não sei')], max_length=2, null=True, verbose_name='81. Algum de seus pais ou responsáveis fuma?'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='questao_82',
            field=models.CharField(blank=True, choices=[('0', 'Sim'), ('1', 'Não')], max_length=2, null=True, verbose_name='82. Alguma vez na vida você tomou uma dose de bebida alcoólica (uma dose equivale a uma lata de cerveja ou uma taça de vinho ou uma dose de cachaça ou uísque etc.)?'),
        ),
    ]
