# Generated by Django 2.1.3 on 2018-11-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0019_auto_20181115_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='questao_69',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum dia nos últimos 7 dias (0 dia)'), ('1', '1 dia nos últimos 7 dias'), ('2', '2 dias nos últimos 7 dias'), ('3', '3 dias nos últimos 7 dias'), ('4', '4 dias nos últimos 7 dias'), ('5', '5 dias nos últimos 7 dias'), ('6', '5 dias mais sábado, nos últimos 7 dias'), ('7', '5 dias mais sábado e domingo, nos últimos 7 dias')], max_length=2, null=True, verbose_name='69. Nos últimos 7 dias, em quantos dias você fez atividade física por pelo menos 60 minutos (1 hora) por dia? (Some todo o tempo que você gastou em qualquer tipo de atividade física, em cada dia)'),
        ),
    ]
