# Generated by Django 2.1.3 on 2018-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0020_questionario_questao_69'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.CharField(choices=[('0', 'Matutino'), ('1', 'Vespertino'), ('2', 'Noturno'), ('3', 'Tempo Integral')], max_length=2, null=True, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='raca',
            field=models.CharField(choices=[('0', 'Amarela'), ('1', 'Branca'), ('2', 'Indígena'), ('3', 'Parda'), ('4', 'Preta')], max_length=2, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('0', 'Masculino'), ('1', 'Feminino'), ('2', 'Outro'), ('3', 'Prefiro não responder')], max_length=2, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=200, null=True, verbose_name='Turma'),
        ),
    ]
