# Generated by Django 2.1.3 on 2018-11-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0023_auto_20181115_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='anotador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Anotador'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_11',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_12',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 12'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_13',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 13'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_14',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 14'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_15',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 15'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_16',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_17',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 17'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_18',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 18'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_21',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 21'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_22',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 22'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_23',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 23'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_24',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 24'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_25',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 25'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_26',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 26'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_27',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_28',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 28'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_31',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_32',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 32'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_33',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 33'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_34',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 34'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_35',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 35'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_36',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_37',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 37'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_38',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 38'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_41',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 41'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_42',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 42'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_43',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 43'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_44',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 44'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_45',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 45'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_46',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 46'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_47',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_coroa_48',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Coroa 48'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_11',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_12',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 12'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_13',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 13'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_14',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 14'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_15',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 15'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_16',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_17',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 17'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_18',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 18'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_21',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 21'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_22',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 22'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_23',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 23'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_24',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 24'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_25',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 25'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_26',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 26'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_27',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_28',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 28'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_31',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_32',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 32'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_33',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 33'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_34',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 34'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_35',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 35'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_36',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_37',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 37'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_38',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 38'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_41',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 41'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_42',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 42'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_43',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 43'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_44',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 44'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_45',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 45'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_46',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 46'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_47',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='carie_tratamento_48',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tratamento 48'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='examinador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Examinador'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_11',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Bolsa periodontal 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_1716',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Bolsa periodontal 17/16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_2627',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Bolsa periodontal 26/27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_31',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Bolsa periodontal 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_3736',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Bolsa periodontal 37/36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_bolsa_4647',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Bolsa periodontal 46/47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_11',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Cálculo dentário 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_1716',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Cálculo dentário 17/16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_2627',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Cálculo dentário 26/27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_31',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Cálculo dentário 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_3736',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Cálculo dentário 37/36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_calculo_4647',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Cálculo dentário 46/47'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_11',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sangramento 11'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_1716',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sangramento 17/16'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_2627',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sangramento 26/27'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_31',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sangramento 31'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_3736',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sangramento 37/36'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='periodontal_sangramento_4647',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sangramento 46/47'),
        ),
    ]
