# Generated by Django 2.1.3 on 2018-11-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0027_auto_20181124_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretor',
            name='questao_37',
            field=models.CharField(blank=True, choices=[('0', 'Refrigerante'), ('1', 'Suco ou refresco natural de frutas'), ('2', 'Bebidas açucaradas (suco artificial, chá gelado, isotônicos, águas com sabor, energéticos, leite de soja etc. Não contar bebida láctea)'), ('3', 'Leite ou bebida a base de leite (excluir leite de soja)'), ('4', 'Salgados fritos (coxinha, pastel, quibe, batata frita etc)'), ('5', 'Salgados assados (pastel, empada, esfirra etc)'), ('6', 'Salgadinhos industrializados vendidos em pacotes, tipo “chips” e outros (incluindo batata frita de pacote)'), ('7', 'Biscoitos ou bolachas salgadas ou doces, balas, confeitos, doces, chocolates, sorvetes, dim-dim, sacolé, chupe-chupe e outros'), ('8', 'Sanduíches (cachorro quente, misto quente, hambúrguer etc)'), ('9', 'Frutas frescas ou salada de frutas')], max_length=2, null=True, verbose_name='37. Que tipos de bebidas e produtos alimentícios são vendidos na cantina? (múltipla resposta)'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='questao_39',
            field=models.CharField(blank=True, choices=[('0', 'Refrigerante'), ('1', 'Suco ou refresco natural de frutas'), ('2', 'Bebidas açucaradas (suco artificial, chá gelado, isotônicos, águas com sabor, energéticos, leite de soja etc. Não contar bebida láctea)'), ('3', 'Leite ou bebida a base de leite (excluir leite de soja)'), ('4', 'Salgados fritos (coxinha, pastel, quibe, batata frita etc)'), ('5', 'Salgados assados (pastel, empada, esfirra etc)'), ('6', 'Salgadinhos industrializados vendidos em pacotes, tipo “chips” e outros (incluindo batata frita de pacote)'), ('7', 'Biscoitos ou bolachas salgadas ou doces'), ('8', 'Balas, confeitos, doces, chocolates, sorvetes, dim-dim, sacolé, chupe-chupe e outros'), ('9', 'Sanduíches (cachorro quente, misto quente, hambúrguer etc)'), ('10', 'Frutas frescas ou salada de frutas')], max_length=2, null=True, verbose_name='39. Que tipos de bebidas e produtos alimentícios são vendidos no ponto alternativo de vendas? (múltipla resposta)'),
        ),
    ]
