# Generated by Django 2.1.3 on 2018-11-26 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0028_auto_20181125_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretor',
            name='questao_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Manhã'), ('1', 'Intermediário'), ('2', 'Tarde'), ('3', 'Noite')], max_length=2), blank=True, null=True, size=None, verbose_name='1. A escola funciona em quais turnos? (múltipla resposta)'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='questao_28',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Deficiência intelectual'), ('1', 'Transtornos do espectro do autismo'), ('2', 'Transtornos mentais e de comportamento'), ('3', 'Deficiência física'), ('4', 'Deficiência auditiva'), ('5', 'Deficiência visual'), ('6', 'Deficiência múltipla (2 ou mais deficiências simultâneas)'), ('7', 'Outros')], max_length=2), blank=True, null=True, size=None, verbose_name='28. Qual(is) tipo(s) de deficiência? (múltipla resposta)'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='questao_3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Educação Infantil (creche, pré-escola)'), ('1', 'Ensino Fundamental (8 anos, 9 anos)'), ('2', 'Ensino Médio (médio, integrado, normal/magistério, educação profissional)'), ('3', 'Educação de Jovens e Adultos (fundamental, projovem urbano, médio)')], max_length=2), blank=True, null=True, size=None, verbose_name='3. A escola atende a quais etapas de ensino? (múltipla resposta)'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='questao_31',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Rampas de acesso'), ('1', 'Interior adequado para locomoção'), ('2', 'Móveis adequados para alunos com necessidades especiais'), ('3', 'Sanitário adequado para alunos com necessidades especiais')], max_length=2), blank=True, null=True, size=None, verbose_name='31. Quais estruturas existem na escola para assegurar a acessibilidade dos alunos com necessidades especiais? (múltipla resposta)'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='questao_33',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Manhã'), ('1', 'Intermediário'), ('2', 'Tarde'), ('3', 'Noite'), ('4', 'Integral'), ('5', 'Internato'), ('6', 'Educação Infantil'), ('7', '1o a 5o ano do Ensino Fundamental'), ('8', '6o a 9o ano do Ensino Fundamental'), ('9', 'Ensino Médio'), ('10', 'Educação de Jovens e Adultos')], max_length=2), blank=True, null=True, size=None, verbose_name='33. A escola oferece comida (merenda escolar / almoço) para alunos de quais turnos e níveis de ensino? (múltipla resposta)'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='questao_37',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Refrigerante'), ('1', 'Suco ou refresco natural de frutas'), ('2', 'Bebidas açucaradas (suco artificial, chá gelado, isotônicos, águas com sabor, energéticos, leite de soja etc. Não contar bebida láctea)'), ('3', 'Leite ou bebida a base de leite (excluir leite de soja)'), ('4', 'Salgados fritos (coxinha, pastel, quibe, batata frita etc)'), ('5', 'Salgados assados (pastel, empada, esfirra etc)'), ('6', 'Salgadinhos industrializados vendidos em pacotes, tipo “chips” e outros (incluindo batata frita de pacote)'), ('7', 'Biscoitos ou bolachas salgadas ou doces, balas, confeitos, doces, chocolates, sorvetes, dim-dim, sacolé, chupe-chupe e outros'), ('8', 'Sanduíches (cachorro quente, misto quente, hambúrguer etc)'), ('9', 'Frutas frescas ou salada de frutas')], max_length=2), blank=True, null=True, size=None, verbose_name='37. Que tipos de bebidas e produtos alimentícios são vendidos na cantina? (múltipla resposta)'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='questao_39',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Refrigerante'), ('1', 'Suco ou refresco natural de frutas'), ('2', 'Bebidas açucaradas (suco artificial, chá gelado, isotônicos, águas com sabor, energéticos, leite de soja etc. Não contar bebida láctea)'), ('3', 'Leite ou bebida a base de leite (excluir leite de soja)'), ('4', 'Salgados fritos (coxinha, pastel, quibe, batata frita etc)'), ('5', 'Salgados assados (pastel, empada, esfirra etc)'), ('6', 'Salgadinhos industrializados vendidos em pacotes, tipo “chips” e outros (incluindo batata frita de pacote)'), ('7', 'Biscoitos ou bolachas salgadas ou doces'), ('8', 'Balas, confeitos, doces, chocolates, sorvetes, dim-dim, sacolé, chupe-chupe e outros'), ('9', 'Sanduíches (cachorro quente, misto quente, hambúrguer etc)'), ('10', 'Frutas frescas ou salada de frutas')], max_length=2), blank=True, null=True, size=None, verbose_name='39. Que tipos de bebidas e produtos alimentícios são vendidos no ponto alternativo de vendas? (múltipla resposta)'),
        ),
    ]
